// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL6th5C6hdHhk6Zy7DWDjJzqJv5amRhhM',
    appId: '1:642153987831:web:4f98961a00167699351df2',
    messagingSenderId: '642153987831',
    projectId: 'minimal-social-app2',
    authDomain: 'minimal-social-app2.firebaseapp.com',
    storageBucket: 'minimal-social-app2.appspot.com',
    measurementId: 'G-KRCG7QJZ0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm0Re-kabt25Q5bpOWAfuWkiiES3g6vRs',
    appId: '1:642153987831:android:0c61aea491a854d7351df2',
    messagingSenderId: '642153987831',
    projectId: 'minimal-social-app2',
    storageBucket: 'minimal-social-app2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKo7dKD1V97LBmig_NjjWG_CvmPIlRFiY',
    appId: '1:642153987831:ios:c2f5ce34a2578d4d351df2',
    messagingSenderId: '642153987831',
    projectId: 'minimal-social-app2',
    storageBucket: 'minimal-social-app2.appspot.com',
    iosBundleId: 'com.example.socialmediaapv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKo7dKD1V97LBmig_NjjWG_CvmPIlRFiY',
    appId: '1:642153987831:ios:431895928b267ac1351df2',
    messagingSenderId: '642153987831',
    projectId: 'minimal-social-app2',
    storageBucket: 'minimal-social-app2.appspot.com',
    iosBundleId: 'com.example.socialmediaapv2.RunnerTests',
  );
}
